config/routes.rb
Rails.application.routes.draw do
  resources :physician_reports

  resources :patient_billings

  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
  get 'physician_reports/index'
  get 'patient_billings/index'
  get 'users/sign_in'
  get 'users/sign_out'
  get 'appointments/index'
  get 'appointments/new'
  get 'patients/index'
  get 'patients/new'
  get 'physicians/index'
  get 'physicians/new'
  get 'codes/index'
  get 'codes/new'

  resources :appointments
  resources :codes
  resources :physicians
  resources :patients
  resources :users
  resources :physician_reports
  resources :patient_billings

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :codes, through: :appointments
  has_many :patients, through: :appointments
  has_many :physician_reports, through: :appointments
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def authenticate
      authenticate_user! && current_user.admin?
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name, :email)
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<h1>Listing physicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        <td><%= physician.email %></td>
        <td><%= link_to 'Show', physician %></td>
        <% if can? :update, physician %>
            <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
            <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New physician</h1>
<% if can? :update, @physician %>
    <%= render 'form' %>
<% end %>
<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @physician.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @physician.email %>
</p>

<% if can? :update, @physician %>
    <%= link_to 'Edit', edit_physician_path(@physician) %> |
<% end %>
<%= link_to 'Back', physicians_path %>