config/routes.rb
Rails.application.routes.draw do
  resources :physician_reports

  resources :patient_billings

  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
  get 'physician_reports/index'
  get 'patient_billings/index'
  get 'users/sign_in'
  get 'users/sign_out'
  get 'appointments/index'
  get 'appointments/new'
  get 'patients/index'
  get 'patients/new'
  get 'physicians/index'
  get 'physicians/new'
  get 'codes/index'
  get 'codes/new'

  resources :appointments
  resources :codes
  resources :physicians
  resources :patients
  resources :users
  resources :physician_reports
  resources :patient_billings

end

app/models/code.rb
class Code < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
  has_many :patients, through: :appointments
  has_one :patient_billing, through: :appointment
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]

  # GET /codes
  # GET /codes.json
  def index
    @codes = Code.all
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
  end

  # GET /codes/new
  def new
    @code = Code.new
  end

  # GET /codes/1/edit
  def edit
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render :show, status: :created, location: @code }
      else
        format.html { render :new }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codes/1
  # PATCH/PUT /codes/1.json
  def update
    respond_to do |format|
      if @code.update(code_params)
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { render :show, status: :ok, location: @code }
      else
        format.html { render :edit }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code.destroy
    respond_to do |format|
      format.html { redirect_to codes_url, notice: 'Code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_code
      @code = Code.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_params
      params.require(:code).permit(:num, :description)
    end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<%= form_for(@code) do |f| %>
  <% if @code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@code.errors.count, "error") %> prohibited this code from being saved:</h2>

      <ul>
      <% @code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :num %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/codes/edit.html.erb
<h1>Editing code</h1>

<%= render 'form' %>

<%= link_to 'Show', @code %> |
<%= link_to 'Back', codes_path %>

app/views/codes/index.html.erb
<h1>Listing codes</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @codes.each do |code| %>
      <tr>
        <td><%= code.num %></td>
        <td><%= number_to_currency(code.price) %></td>
        <td><%= link_to 'Show', code %></td>
        <% if can? :update, code %>
            <td><%= link_to 'Edit', edit_code_path(code) %></td>
            <td><%= link_to 'Destroy', code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Code', new_code_path %>

app/views/codes/new.html.erb
<h1>New code</h1>
<% if can? :update, @code %>
    <%= render 'form' %>
<% end %>
    <%= link_to 'Back', codes_path %>

app/views/codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @code.num %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@code.price) %>
</p>

<% if can? :update, @code %>
    <%= link_to 'Edit', edit_code_path(@code) %> |
<% end %>
<%= link_to 'Back', codes_path %>