config/routes.rb
Rails.application.routes.draw do
  resources :physician_reports

  resources :patient_billings

  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
  get 'physician_reports/index'
  get 'patient_billings/index'
  get 'users/sign_in'
  get 'users/sign_out'
  get 'appointments/index'
  get 'appointments/new'
  get 'patients/index'
  get 'patients/new'
  get 'physicians/index'
  get 'physicians/new'
  get 'codes/index'
  get 'codes/new'

  resources :appointments
  resources :codes
  resources :physicians
  resources :patients
  resources :users
  resources :physician_reports
  resources :patient_billings

end

app/models/patient_billing.rb
class PatientBilling < ActiveRecord::Base
  belongs_to :appointment
  has_many :codes, through: :appointment
  has_many :patients, through: :appointment
end

app/controllers/patient_billings_controller.rb
class PatientBillingsController < ApplicationController
  before_action :set_patient_billing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]

  respond_to :html

  def index
    @patient_billings = PatientBilling.all
    respond_with(@patient_billings)
  end

  def show
    respond_with(@patient_billing)
  end

  def new
    @patient_billing = PatientBilling.new
    respond_with(@patient_billing)
  end

  def edit
  end

  def create
    @patient_billing = PatientBilling.new(patient_billing_params)
    @patient_billing.save
    respond_with(@patient_billing)
  end

  def update
    @patient_billing.update(patient_billing_params)
    respond_with(@patient_billing)
  end

  def destroy
    @patient_billing.destroy
    respond_with(@patient_billing)
  end

  private
    def set_patient_billing
      @patient_billing = PatientBilling.find(params[:id])
    end

    def patient_billing_params
      params.require(:patient_billing).permit(:appointment_id)
    end
end

app/helpers/patient_billings_helper.rb
module PatientBillingsHelper
end

app/views/patient_billings/_form.html.erb
<%= form_for(@patient_billing) do |f| %>
  <% if @patient_billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient_billing.errors.count, "error") %> prohibited this patient_billing from being saved:</h2>

      <ul>
      <% @patient_billing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :appointment_id %><br>
      <%= f.collection_select :appointment_id,Appointment.all,:id,:date %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patient_billings/edit.html.erb
<h1>Editing patient_billing</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient_billing %> |
<%= link_to 'Back', patient_billings_path %>

app/views/patient_billings/index.html.erb
<h1>Listing Patient Billings</h1>

<table>
  <thead>
    <tr>
      <th>Appointment</th>
      <th>Invoice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient_billings.each do |patient_billing| %>
      <tr>
        <td><%= patient_billing.appointment.date %></td>
        <td><%= number_to_currency(patient_billing.appointment.code.price) %></td>
        <td><%= link_to 'Show', patient_billing %></td>
        <td><%= link_to 'Edit', edit_patient_billing_path(patient_billing) %></td>
        <td><%= link_to 'Destroy', patient_billing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient billing', new_patient_billing_path %>

app/views/patient_billings/new.html.erb
<h1>New patient_billing</h1>

<%= render 'form' %>

<%= link_to 'Back', patient_billings_path %>

app/views/patient_billings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Appointment:</strong>
  <%= @patient_billing.appointment.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @patient_billing.appointment.patient.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient_billing.appointment.patient.email %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= number_to_currency(@patient_billing.appointment.code.price) %>
</p>

<%= link_to 'Edit', edit_patient_billing_path(@patient_billing) %> |
<%= link_to 'Back', patient_billings_path %>