config/routes.rb
Rails.application.routes.draw do
  resources :physician_reports

  resources :patient_billings

  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
  get 'physician_reports/index'
  get 'patient_billings/index'
  get 'users/sign_in'
  get 'users/sign_out'
  get 'appointments/index'
  get 'appointments/new'
  get 'patients/index'
  get 'patients/new'
  get 'physicians/index'
  get 'physicians/new'
  get 'codes/index'
  get 'codes/new'

  resources :appointments
  resources :codes
  resources :physicians
  resources :patients
  resources :users
  resources :physician_reports
  resources :patient_billings

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    elsif user.doctor? || user.officeworker?
      can :manage, Appointment
      can :manage, PatientBilling
    else
      can :create, Appointment
      can :create, Patient
      can :destroy, Appointment do |appointment|
        appointment.try(:user) == user
      end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :code
  has_many :patient_billings
  has_many :physician_reports
end

app/models/code.rb
class Code < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
  has_many :patients, through: :appointments
  has_one :patient_billing, through: :appointment
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments
  has_many :physicians, through: :appointments
  has_many :codes, through: :appointments
  has_many :patient_billings, through: :appointments
end

app/models/patient_billing.rb
class PatientBilling < ActiveRecord::Base
  belongs_to :appointment
  has_many :codes, through: :appointment
  has_many :patients, through: :appointment
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :codes, through: :appointments
  has_many :patients, through: :appointments
  has_many :physician_reports, through: :appointments
end

app/models/physician_report.rb
class PhysicianReport < ActiveRecord::Base
  belongs_to :appointment
  has_many :codes, through: :appointment
  has_many :physicians, through: :appointment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]

  # GET /codes
  # GET /codes.json
  def index
    @codes = Code.all
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
  end

  # GET /codes/new
  def new
    @code = Code.new
  end

  # GET /codes/1/edit
  def edit
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(code_params)

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render :show, status: :created, location: @code }
      else
        format.html { render :new }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /codes/1
  # PATCH/PUT /codes/1.json
  def update
    respond_to do |format|
      if @code.update(code_params)
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { render :show, status: :ok, location: @code }
      else
        format.html { render :edit }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
    @code.destroy
    respond_to do |format|
      format.html { redirect_to codes_url, notice: 'Code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_code
      @code = Code.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_params
      params.require(:code).permit(:num, :description)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource except: [:create]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/invoice_helper.rb
module InvoiceHelper
end

app/helpers/patient_billings_helper.rb
module PatientBillingsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>CIS4339Project</title>
  <%= stylesheet_link_tag    'application', media: 'screen', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'shared/nav' %>

<header>
  <h1><%= link_to "Professional Dermitology", welcome_index_path %></h1>
  <p><b>Filler text here</b></p>
</header>

<div id="content">

<%= yield %>

</div>

<aside>

  <section>
    <h3>Administrative</h3>
    <ul>
      <li><%= link_to "Patient Billings", patient_billings_path %></li>
      <li><%= link_to "Reports", physician_reports_path %></li>
      <li><a href>Diagnostic Codes</a>
        <ul>
        <li><%= link_to "New Code", codes_new_path(@code) %></li>
        <li><%= link_to "Edit Code", codes_index_path(@code) %></li>
        </ul>
      </li>
    </ul>
  </section>

  <section>
    <h3>Contact Information</h3>
    <ul>
      <li>Office Phone: (123)555-1234</li>
      <li>Emergency Phone: (123)555-2345</li>
      <li>Email: doctor@office.com</li>
    </ul>
  </section>

</aside>

<footer>
  <br />
  <p>&copy; 2014 Lucas Phan</p>
</footer>

</body>
</html>

app/views/shared/_nav.html.erb
<nav><!-- top nav -->
  <div class="menu">
    <ul>
      <li><a href>Appointments</a>
        <ul>
          <li><%= link_to "New Appointment", appointments_new_path %></li>
          <li><%= link_to "Edit Appointment", appointments_index_path %></li>
        </ul>
      </li>
      <li><a href>Patients</a>
        <ul>
          <li><%= link_to "New Patient", patients_new_path %></li>
          <li><%= link_to "Edit Patient", patients_index_path %></li>
        </ul>
      </li>
      <li><a href>Physicians</a>
        <ul>
        <li><%= link_to "New Physician", physicians_new_path(@physician) %></li>
        <li><%= link_to "Edit Physician", physicians_index_path(@physician) %></li>
        </ul>
      </li>
      <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path %></li>
      <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav><!-- end of top nav -->
